spring:
  application:
    name: CINEMA_BOOKING_BACKEND
  datasource:
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
security:
  jwt:
    signerKey: "zV6pL9bK2N8xM4jR7fW3aQ5sD1gH0hJ2kL4mN6bV8pQ0wE1rT3yU5iO7pA9sD1fG"
    access-token-expiry: 3600 # 1 giờ (giây)
    refresh-token-expiry: 604800 # 7 ngày (giây)


